In [3]:
import numpy as np

a: np.ndarray = np.array([1, 2, 3])
print(type(a))
print(a.ndim)
print(a.shape)
print(a.itemsize)
print(a.size)
print(a.data)

<class 'numpy.ndarray'>
1
(3,)
8
3


In [7]:
zeros = np.ndarray = np.zeros((1, 5), dtype=np.int16)
print(zeros.itemsize)
print(zeros)

2
[[0 0 0 0 0]]


In [8]:
ones = np.ndarray = np.ones((2, 3), dtype=np.int32)
print(ones.itemsize)
print(ones)

4
[[1 1 1]
 [1 1 1]]


In [9]:
range_1: np.ndarray = np.arange(10, 30, 2)
print(range_1)

[10 12 14 16 18 20 22 24 26 28]


In [6]:
range_2: np.ndarray = np.linspace(0, 5, 9)
print(range_2)

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375 5.   ]


In [13]:
# basic operations in array -> apply to elements
arr_1: np.ndarray = np.array([2, 3, 4, 5])
arr_2: np.ndarray = np.array([1, 2, 4, 3])
arr_3 = arr_1 - arr_2
print(arr_3)

arr_4 = arr_1 * arr_2
print(arr_4)

[1 1 0 2]
[ 2  6 16 15]


In [25]:
# matrix
A: np.ndarray = np.array([[1, 1],
              [2, 1]])
B: np.ndarray = np.array([[3, 0],
                [3, 5]])

print(A * B)
print(A@B)
print(A.dot(B))

[[3 0]
 [6 5]]
[[6 5]
 [9 5]]
[[6 5]
 [9 5]]


In [40]:
# random
rg = np.random.default_rng(1)
a = rg.random((2, 3))
print(a)

b = np.random.randint(1, 100)
print(b)

c = np.random.randint(100, size=(3, 5))
print(c)

[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]
39
[[88 53 29 37 26]
 [18 59 41 80 71]
 [ 3 76 45  1 71]]
