ex1: Viết chương trình nhập vào số nguyên dương n từ bàn phím, kiểm tra xem n có phải là số
siêu nguyên tố hay không?
Số siêu nguyên tố là số nguyên tố mà khi bỏ 1 số tùy ý các chữ số bên phải của nó thì phần
còn lại vẫn là số nguyên tố.

In [12]:
import math


def check(x):
    if x == 2:
        return True
    for i in range(2, x):
        if x % i == 0:
            return False
        return True


n = int(input('nhap vao so nguyen n: '))


def check_rm_end(n):
    if not check(n):
        return False
    rm_end = n // 10
    while rm_end > 0:
        print('start loop rm_end', rm_end)
        if not check(rm_end):
            print('check false', rm_end)
            return False
        rm_end = rm_end // 10
        print('update rm_end', rm_end)
    return True


check_rm_end(n)
# print(check_rm_end(n))

start loop rm_end 4
check false 4


False

ex2: Viết chương trình (Pitago.py) thực hiện việc nhập số nguyên n, liệt kê các số nguyên a, b, c
trong đoạn [1, n] để bộ 3 (a, b, c) lập thành bộ Pitago.
a, b, c được sắp theo thứ tự tăng dần (a <= b <= c), mỗi bộ trên 1 dòng theo mẫu

In [17]:
n = int(input('enter integer n: '))


def find_pythagore(m):
    result = []
    for a in range(1, n + 1):
        for b in range(a, n + 1):
            for c in range(b, n + 1):
                if a ** 2 + b ** 2 == c ** 2:
                    result.append((a, b, c))
    return result


for rs in find_pythagore(n):
    print(rs)

(3, 4, 5)
(5, 12, 13)
(6, 8, 10)
(7, 24, 25)
(8, 15, 17)
(9, 12, 15)
(9, 40, 41)
(10, 24, 26)
(11, 60, 61)
(12, 16, 20)
(12, 35, 37)
(13, 84, 85)
(14, 48, 50)
(15, 20, 25)
(15, 36, 39)
(16, 30, 34)
(16, 63, 65)
(18, 24, 30)
(18, 80, 82)
(20, 21, 29)
(20, 48, 52)
(21, 28, 35)
(21, 72, 75)
(24, 32, 40)
(24, 45, 51)
(24, 70, 74)
(25, 60, 65)
(27, 36, 45)
(28, 45, 53)
(28, 96, 100)
(30, 40, 50)
(30, 72, 78)
(32, 60, 68)
(33, 44, 55)
(33, 56, 65)
(35, 84, 91)
(36, 48, 60)
(36, 77, 85)
(39, 52, 65)
(39, 80, 89)
(40, 42, 58)
(40, 75, 85)
(42, 56, 70)
(45, 60, 75)
(48, 55, 73)
(48, 64, 80)
(51, 68, 85)
(54, 72, 90)
(57, 76, 95)
(60, 63, 87)
(60, 80, 100)
(65, 72, 97)


ex3: Nhập 1 số n tương ứng số input, sau đó nhập tiếp n số trong khoảng [1,n], tìm các số trong
khoảng [1,n] không xuất hiện

In [20]:
n = int(input('enter integer n: '))
compare_lst = input('enter n number in range: ').split()

for i in range(n):
    compare_lst[i] = int(compare_lst[i])

origin = list(range(1, n + 1))

res = []
for e in origin:
    if not compare_lst.__contains__(e):
        res.append(e)

print(res)


[]


Bài 4
Cho 1 array chứa các khoảng (intervals) trong đó
intervals[i] = [starti, endi].
Viết 1 function merge các khoảng bị overlap để trả ra 1 array chứa các khoảng không bị
overlap với nhau mà vẫn cover được tất cả các khoảng ban đầu
Điều kiện:
 1 <= intervals.length <= 10 4
 intervals[i].length == 2
 0 <= start i <= end i <= 10 4

In [42]:
import numpy as np

my_lst = [[1, 4],
          [3, 5],
          [10, 20],
          [4, 30],
          [11, 15],
          [16, 30],
          [32, 50],
          [48, 51]]

mat = np.array(my_lst)

mat = mat[mat[:, 0].argsort()]
print(mat)

res = np.array([[mat[0, 0], mat[0, 1]]])
j = 0
for i in range(len(mat) - 1):
    if mat[i + 1, 0] <= res[j, 1]:
        res[j, 1] = max(mat[i + 1, 1],res[j,1])
    else:
        res = np.vstack([res, mat[i + 1, :]])
        j += 1

print(res)

[[ 1  4]
 [ 3  5]
 [ 4 30]
 [10 20]
 [11 15]
 [16 30]
 [32 50]
 [48 51]]
[[ 1 30]
 [32 51]]


Bài 7 Cho 1 dictionary gồm (a-z và khoảng trắng) và encode (mã hóa) của nó là số từ 0-26.
{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o':
14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25, ' ': 26}
Nếu các ký tự không có trong từ điển, được encode (mã hóa ) = -1
Viết chương trình đọc file text(chú ý là file chỉ gồm 1 câu text) và trả về numpy array gồm
các số tương ứng với các chữ cái tạo thành nó. Ví dụ nhập "abc" trả vê [0, 1, 2]

In [45]:
import numpy as np
def encode():
    with open('test.txt') as f:
        contents = f.read()
        print(contents)
    dict = {'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25, ' ': 26}
    a = np.array([], dtype= int)
    for i in contents:
        if i not in dict.keys():
            a = np.append(a,[-1])
        else:
            a =np.append(a, [dict.get(i)])
    return a
arr = encode()
print(arr,sep=',')

hello dai ca Linh
[ 7  4 11 11 14 26  3  0  8 26  2  0 26 -1  8 13  7]


Bài 10. Thay thế mảng a gồm các giá trị chẵn trong mảng từ 1 đến 51 bằng 2, nhưng không
làm thay đổi mảng ban đầu bằng mảng b. In ra mảng b.

In [47]:
import numpy as np

a = np.arange(1, 52)
b = np.copy(a)

b[b%2==0] = 2
print(b)

[ 1  2  3  2  5  2  7  2  9  2 11  2 13  2 15  2 17  2 19  2 21  2 23  2
 25  2 27  2 29  2 31  2 33  2 35  2 37  2 39  2 41  2 43  2 45  2 47  2
 49  2 51]


Bài 11. Đảo ngược mảng 2 chiều. Cho mảng 2 chiều arr thực hiện đảo ngược
thứ tự của mảng 2 chiều. Đảo ngược thứ tự các cột, đảo ngược thứ tự các hàn tạo ra mảng c
mới. In ra mảng c.

In [51]:
c = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

# flip both columns and rows
# add param axis for column or row
c = np.flip(c)

print(c)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


Bài 12. Thay thế mảng a gồm các giá trị lẻ trong mảng từ 100 đến 200 bằng 0, nhưng không
làm thay đổi mảng ban đầu bằng mảng b. In ra mảng b.

In [52]:
a = np.arange(100, 201)
b = np.copy(a)
b[b%2 == 1] = 0
print(b)

[100   0 102   0 104   0 106   0 108   0 110   0 112   0 114   0 116   0
 118   0 120   0 122   0 124   0 126   0 128   0 130   0 132   0 134   0
 136   0 138   0 140   0 142   0 144   0 146   0 148   0 150   0 152   0
 154   0 156   0 158   0 160   0 162   0 164   0 166   0 168   0 170   0
 172   0 174   0 176   0 178   0 180   0 182   0 184   0 186   0 188   0
 190   0 192   0 194   0 196   0 198   0 200]



Bài 1: Tìm min của hàm  𝑓(𝑥)=𝑥^2−12𝑥+20

In [53]:
from scipy.optimize import minimize

def function(x):
    return x**2 - 12*x + 20

result_function = minimize(function, 0, method = 'BFGS')
result_function

      fun: -15.9999999999999
 hess_inv: array([[0.49999997]])
      jac: array([-9.53674316e-07])
  message: 'Optimization terminated successfully.'
     nfev: 8
      nit: 3
     njev: 4
   status: 0
  success: True
        x: array([5.99999969])

Tìm min của hàm mục tiêu: $x_1^2 + x_1 x_2$
với các ràng buộc:
$$\begin{cases} x_1^3 + x_1 x_2 = 100 \\ x_1^2 + x_2 \geq 50 \\ -100 \leq x_1, x_2 \leq 100
\end{cases}$$

In [54]:
def objective(x):
    x1 = x[0]
    x2 = x[1]
    return x1**2 + x1*x2

def equality_constraint(x):
    x1 = x[0]
    x2 = x[1]
    return x1**3 + x1*x2 - 100

def inequality_constraint(x):
    x1 = x[0]
    x2 = x[1]
    return x1**2 + x2 - 50

bounds_x1 = (-100, 100)
bounds_x2 = (-100, 100)
bounds = (bounds_x1, bounds_x2)

constraint1 = {'type':'eq','fun':equality_constraint}
constraint2 = {'type':'ineq','fun': inequality_constraint}
constraint = [constraint1,constraint2]

x0 = [1,1]

result = minimize(objective, x0, method = 'SLSQP', bounds = bounds, constraints = constraint)

result

     fun: 96.00000027660178
     jac: array([50.00000095,  2.        ])
 message: 'Optimization terminated successfully'
    nfev: 32
     nit: 10
    njev: 10
  status: 0
 success: True
       x: array([ 1.99999997, 46.00000084])

In [57]:
def function(x):
    return -x[0] - 2*x[1]

def ineq(x):
    return 6 - x[0] - 2*x[1]

bounds_x1 = (1,5)
bounds_x2 = (1,5)
bounds = (bounds_x1, bounds_x2)

constraint = [{'type': 'ineq', 'fun': ineq}]
x0 = [-2,2]
result = minimize(function, x0, method='SLSQP', bounds=bounds, constraints=constraint)

result

     fun: -5.999999999999998
     jac: array([-1., -2.])
 message: 'Optimization terminated successfully'
    nfev: 6
     nit: 2
    njev: 2
  status: 0
 success: True
       x: array([1.2, 2.4])

In [58]:
from scipy import optimize

optimize.linprog(
    c = [-1, -2],
    A_ub=[[1, 2]],
    b_ub=[6],
    bounds=(1, 5),
    method='simplex'
)

     con: array([], dtype=float64)
     fun: -6.0
 message: 'Optimization terminated successfully.'
     nit: 3
   slack: array([0.])
  status: 0
 success: True
       x: array([1. , 2.5])