In [9]:
import numpy as np

In [3]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [34]:
import numpy as np
from scipy.sparse.linalg import minres

np.random.seed(100)
A = np.random.randint(1, 10, (100,100))
A = A + A.T
print(A)
b = np.random.randint(1, 10, 100)
x, exitCode = minres(A, b, maxiter=1000, show=True)
print(exitCode)
np.allclose(A.dot(x), b)

[[18 17  9 ...  8  8 16]
 [17  4 10 ... 12  8 13]
 [ 9 10 16 ... 13 11  6]
 ...
 [ 8 12 13 ... 10  7 12]
 [ 8  8 11 ...  7 10 10]
 [16 13  6 ... 12 10  2]]
Enter minres.   Solution of symmetric Ax = b
Enter minres.   n      =  100     shift  =     0.00000000000000e+00
Enter minres.   itnlim =  1000     rtol   =     1.00e-05



   Itn     x(1)     Compatible    LS       norm(A)  cond(A) gbar/|A|
     1  9.95381e-04  5.068e-01  9.979e-01  9.0e+02  1.0e+00  8.9e-01
     2  1.22898e-02  3.710e-01  3.486e-02  1.0e+03  2.3e+01  3.8e-03
     3  7.72113e-04  4.625e-02  3.480e-02  1.0e+03  2.3e+01 -3.5e-02
     4  2.76603e-03  4.287e-02  2.436e-02  1.0e+03  2.6e+01 -5.4e-03
     5  4.50232e-02  2.916e-02  2.396e-02  1.0e+03  2.6e+01  2.3e-02
     6  4.46296e-02  2.855e-02  1.674e-02  1.0e+03  2.7e+01  2.4e-03
     7  7.30801e-02  2.154e-02  1.681e-02  1.0e+03  2.7e+01 -1.7e-02
     8  7.63729e-02  2.107e-02  1.433e-02  1.0e+03  2.7e+01 -2.5e-03
     9  1.07307e-01  1.718e-02  1.396e-02  1.0e+03

False

In [37]:
import numpy as np
from scipy.sparse.linalg import gmres

np.random.seed(100)
A = np.random.randint(1, 10, (100,100))
A = A + A.T
print(A)
b = np.random.randint(1, 10, 100)

x, exitCode = gmres(A, b, maxiter=1000)
print(exitCode)
np.allclose(A.dot(x), b)

[[18 17  9 ...  8  8 16]
 [17  4 10 ... 12  8 13]
 [ 9 10 16 ... 13 11  6]
 ...
 [ 8 12 13 ... 10  7 12]
 [ 8  8 11 ...  7 10 10]
 [16 13  6 ... 12 10  2]]
0


False