In [2]:
import numpy as np

In [4]:
num1 = np.zeros(5)
num2 = np.ones((5,3))
num3 = np.arange(1, 5, 0.5)
num3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [10]:
x1 = np.random.rand(3, 4)
x1

x2 = np.random.randint(3, 6, size=(2, 3))
x2

array([[5, 4, 3],
       [3, 5, 5]])

In [11]:
np.ndim(x1)

2

In [12]:
num = np.arange(0, 100, 1)
num[0:99:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])